wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.6
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.9.15
    start_time: 1670594668.34708
    t:
      1:
      - 55
      2:
      - 53
      - 55
      3:
      - 23
      4: 3.9.15
      5: 0.13.6
      8:
      - 1
      - 5
