name: eda
channels:
  - conda-forge
  - defaults
dependencies:
  - jupyterlab=3.5.1
  - seaborn=0.11.1
  - pandas=1.2.3
  - pip=20.3.3
  - pandas-profiling=3.5.0
  - pyarrow=2.0
  - pip:
      - wandb==0.13.6
